### ISSUE TITLE
跟element-ui不兼容

### ISSUE THREAD

**Issue by zzzgit** [zhuowenli/vue-clipboards#11]
element-ui的dialog，内容不是马上渲染的，只会在第一次open之后，才会渲染
这个插件，在dialog中，不生效，在其他地方，正常
可否修复一下这个bug？调用directive的时候，检查一下是否已经成功初始化，如果没有，尝试再去初始化一次？

**Comment by zhuowenli** [comment]
看了下 clipboard.js 的 issue，上面也有类似的问题：
https://github.com/zenorocha/clipboard.js/issues/155

不过在v1.7.0中有提供了解决方案：
https://github.com/zenorocha/clipboard.js/pull/368#pullrequestreview-23569112

我这边也把相关依赖升级到1.7.1了，同时会去尝试添加一个 `container` 配置来解决这个问题。

保险起见，你可以在弹窗中调用这个directive的时候，给他加一个 `model` 属性，把dialog的class传进来：
![image](https://user-images.githubusercontent.com/9620783/28254004-699134ce-6adb-11e7-829d-197dd57447e1.png)
