### ISSUE TITLE
Add feature to copy/cut dynamic text

### ISSUE THREAD

**Issue by vinh123456789** [zhuowenli/vue-clipboards#16]
Clipboard.js have a feature to copy/cut dynamic text
```
new Clipboard('.btn', {
    text: function(trigger) {
        return trigger.getAttribute('aria-label');
    }
});
```
I wonder if this feature exist in vue-clipboards, if not, it would be great if you can add this feature. Thank you.

**Comment by zhuowenli** [comment]
Can you tell me what kind of scene you use it? 🙂

**Comment by vinh123456789** [comment]
Sure.
There is a feature in my app that export the customer's items prices and the total (quantity are not show) in a specific format, it look like below:
```
Item A: 5 | Item B: 25 | => Total: 550
```
The "Total" value is calculate when i click the copy button.
I want to copy the line above, paste and send it to my customers using instant message.

**Comment by zhuowenli** [comment]
Hmm, maybe you do not need to add an new attributes, calculate it directly inside？

```html
button(v-clipboard="`Item A: ${a} | Item B: ${b} | => Total: ${a * 100 + b * 2}`")
```

**Comment by vinh123456789** [comment]
I did thought about that, but the items are dynamic. User can add, remove items and edit items properties like quanlity, price, etc...
Calculate the whole list of items every time user change some thing seem a bit waste of resource....

**Comment by zhuowenli** [comment]
if use it with `computed` ? 💡 

https://codepen.io/zhuowenli/pen/mMJxWQ?editors=1011

**Comment by vinh123456789** [comment]
`computed` can do this. But as i said, if i use `computed`, each time user make changes to the items list, the whole list get re-calculate:
https://codepen.io/vinh123456789/pen/prJOvw?editors=1011

**Comment by zhuowenli** [comment]
I have a idea, if it can be passed directly to a `function`.

https://github.com/zhuowenli/vue-clipboards/blob/dev/src/vue-clipboards.js#L28-L40

```html
<button v-clipboard="onCopyAction">Copy</button>
```

```js
new Vue({
    data() {
        return {
            value: 1
        }
    },
    methods: {
        onCopyAction() {
            return this.value + 1;
        }
    }
});
```
May be able to solve your problem.

**Comment by vinh123456789** [comment]
It look like what i'm looking for, thank you for your work :))
