### ISSUE TITLE
Container is not defined at ^1.0.3 [solved in 1.0.5]

### ISSUE THREAD

**Issue by alvaromoo** [zhuowenli/vue-clipboards#17]
I've been using your plugin successfully in my work set-up for a while, but when I run my repository in my home set-up they throw me an error: 

`Uncaught TypeError: Cannot read property 'addEventListener' of null`

It appears exactly at this point:

`this.fakeHandler = this.container.addEventListener('click', this.fakeHandlerCallback) || true;`

Looks like `this.container` is `null`

If you need more info just tell me.

Thanks a lot!

UPDATE:
I confirm you 1.0.2 (version that I had installed in my work set-up) works properly :)

**Comment by zhuowenli** [comment]
I still can't reproduce this, maybe providing a repo to reproduce this would be nice

**Comment by mirshko** [comment]
I am able to reproduce this with my repo as well. Version 1.0.4

https://github.com/buildbetterCTAs/app.responsivectabuilder.com/blob/movedToVueClipboards/src/components/embeder.vue#L11

**Comment by zhuowenli** [comment]
Thx, the repo is helpful, and I fixed it with 1.0.5. 😃

**Comment by alvaromoo** [comment]
Thanks you very much!
