### ISSUE TITLE
Failed to resolve directive: clipboard 

### ISSUE THREAD

**Issue by Lanceloft** [zhuowenli/vue-clipboards#2]
use vuex,
`import VueClipboards from 'vue-clipboards';
export default {
  data() {
    return {
      copyData: 'copy data'
    };
  },

components: { VueClipboards },
};`

`<button v-clipboard="copyData" @success="handleSuccess">复制</button>`
显示
[Vue warn]: Failed to resolve directive: clipboard 
(found in anonymous component - use the "name" option for better debugging messages.)

**Comment by zhuowenli** [comment]
can you try putting `Vue.use(VueClipboards)` in the import statement?
repro:

```js
import Vue from 'Vue';
import VueClipboards from 'vue-clipboards';
import App from './components/App.vue';

Vue.use(VueClipboards);

const app = new Vue({
    el: '#app',
    render: h => h(App)
});
```

**Comment by acidjazz** [comment]
@Lanceloft was this what you did to resolve this? I still am getting this error
