### ISSUE TITLE
一个模块只能创建一个clipboards实例

### ISSUE THREAD

**Issue by abel-oye** [zhuowenli/vue-clipboards#22]
一个模块只能创建一个clipboards实例， 你是通过 const clipboards = {}; 保存实例，后来初始化就会将clipboards.destory 
![image](https://user-images.githubusercontent.com/6419673/31953628-10fa6094-b8a9-11e7-8196-98671d9ed45c.png)
截图是两个地方的调用值不一样，最后一次update的对象是上一次的对象 结果被destory啦

**Comment by zhuowenli** [comment]
每个clipboards实例给他绑定一个key试试：https://github.com/zhuowenli/vue-clipboards#multiple

**Comment by abel-oye** [comment]
首先我的场景不是repeat，既然你给出了，从代码角度你那样不解决问题，
![image](https://user-images.githubusercontent.com/6419673/31979860-89146b82-b90e-11e7-99e8-14d861eb3665.png)
我特意做了一个例子。即使是repeat，你也是后一次直接使用上一次的对象
destory

**Comment by abel-oye** [comment]
补充一下：我上面提到问题，核心在update，如果你的值事先定义了不会改变，不会遇见我这个问题，如果这个值是变换这个问题就出现了，你可以review一下

**Comment by zhuowenli** [comment]
已经优化了，欢迎测试。
