### ISSUE TITLE
If create 2 or more buttons with the same bindings. Only the last button will copy updated value

### ISSUE THREAD

**Issue by AlexRadch** [zhuowenli/vue-clipboards#27]
I created 2 buttons with the same bindings.
Now if you change value, than only the last button will copy updated value to clipboard.
All other buttons will copy initial value always.
```vue
<template>
  <div>
    <input v-model="value" />
    <button v-clipboard="value">Copy 1</button>
    <button v-clipboard="value">Copy 2</button>
  </div>
</template>

<script>
export default {
  data () {
    return {
      value: 'Change me'
    }
  }
}
</script>
```

**Comment by zhuowenli** [comment]
https://jsfiddle.net/qhxj441v/

It work at vue-clipboards@1.2.1, maybe you should upgrade it
