### ISSUE TITLE
vue-clipboards v1.2.3 text is not allowed to be falsy

### ISSUE THREAD

**Issue by FerrielMelarpis** [zhuowenli/vue-clipboards#33]
#### Description
- Given that the text to be copied is initially an empty string, e.g. (from an <input> element),
  or the value passed to `v-clipboard` directive is `0`, it will throw an invalid value error.
```
Uncaught (in promise) Error: [vue-clipboards] Invalid value. Please use a valid value.
```
#### Repro
- https://github.com/FerrielMelarpis/repro-vue-clipboards/pull/1

**Comment by zhuowenli** [comment]
all right, I get it...😂

**Comment by truemoroz** [comment]
It's not fixed
