### ISSUE TITLE
Could I copay all content of `div tag`?

### ISSUE THREAD

**Issue by thearabbit** [zhuowenli/vue-clipboards#35]
I would like to copay all content of div tag like this
```
<div id="copyHear">
   <h1>Hello</h1>
   <table>.......
   .........
</div>
```

**Comment by andrey-prokhorov** [comment]
It looks like this functionality is missing in this project, but you can check [this answer](https://stackoverflow.com/questions/52274735/cannot-save-formatted-data-text-html-in-the-clipboard-in-safari) to do it in your own code.
