### ISSUE TITLE
父级有点击事件，怎么阻止冒泡？

### ISSUE THREAD

**Issue by AceYangWQ** [zhuowenli/vue-clipboards#36]
父级有点击事件，怎么阻止冒泡？

**Comment by zhuowenli** [comment]
暂时没有想到好方法，你可以先加个 `@click.stop="() => {}"` 手动阻止下。

```pug
.btn(v-clipboard="onCopy" @click.stop="() => {}")
```

**Comment by AceYangWQ** [comment]
加了还是不行

**Comment by zhuowenli** [comment]
我试了下，是可以的：https://jsfiddle.net/qrgb3xmh/3/ 

要不你写个 demo？

**Comment by AceYangWQ** [comment]
我是@dblclick 所以不行    https://jsfiddle.net/qrgb3xmh/10/

**Comment by zhuowenli** [comment]
那你子级也用 dblclick 来阻止吧 😂这种情况真的蛋疼。。

**Comment by AceYangWQ** [comment]
哈哈，能解决就行
