### ISSUE TITLE
Uncaught (in promise) Error: [vue-clipboards] Invalid value

### ISSUE THREAD

**Issue by YiniXu9506** [zhuowenli/vue-clipboards#39]
hello～ 我在vue template 中使用的 v-if 的判断条件，所以在周期 updated() 之前，有些数据没有拿到，但是 dom 已经加载好了，所以就会报这个错误。于是我在 mounted() 里生成了假的数据放在 dom 里，但是还是会持续报这个错误。请问我该怎么避免这个错误的。谢谢！

**Comment by HackZZ** [comment]
> hello～ 我在vue template 中使用的 v-if 的判断条件，所以在周期 updated() 之前，有些数据没有拿到，但是 dom 已经加载好了，所以就会报这个错误。于是我在 mounted() 里生成了假的数据放在 dom 里，但是还是会持续报这个错误。请问我该怎么避免这个错误的。谢谢！

检查下数据类型，如果是object会一直报这个错
