### ISSUE TITLE
Error Handling - Disabled Input Field

### ISSUE THREAD

**Issue by amorriscode** [zhuowenli/vue-clipboards#5]
Hi there!

I was trying to use vue-clipboards but was having trouble with it. I decided to go with my own implementation of clipboard.js. When implementing clipboard.js, I was given an error that I couldn't copy from an input box because I had a "disabled" attribute on it. I had to switch the attribute to be "readonly" instead.

I am not sure if there are any other valuable errors, but it would have been nice if vue-clipboards would have told me about this error. I would love to try and implement this myself but I am not sure how long it would take me.

Cheers!
- AM

**Comment by zhuowenli** [comment]
I will close this because vue-clipboards is based on [dynamically set a text](https://github.com/zenorocha/clipboard.js#advanced-options).
