### ISSUE TITLE
当我用了两次时，我发现，只有最后一个生效，第一个按钮点了没反应

### ISSUE THREAD

**Issue by scTaoFelix** [zhuowenli/vue-clipboards#7]
当我用了两次时，我发现，只有最后一个生效，第一个按钮点了没反应：
         <p class="line-h-32">AppID: {{ this.AppID }}<el-button :plain="true" @click="open2" class="copy-app-btn" v-clipboard="AppID">复制</el-button></p>
        <p class="line-h-32">Secret: {{ this.Secret }}<el-button :plain="true" @click="open2" class="copy-app-btn" v-clipboard="Secret">复制</el-button></p>

第二个却可以复制成功

**Comment by zhuowenli** [comment]
已经在最新版本解决了~ :P

重复使用时，可以给每个按钮绑定一个单独的key，作为区分：
https://github.com/zhuowenli/vue-clipboards/blob/master/example/App.vue#L8

下面是demo：
https://zhuowenli.github.io/vue-clipboards/

**Comment by cpm828** [comment]
@zhuowenli 

我使用了最新的版本1.0.0，但是还有会有这个问题
